"""group alerts

Revision ID: 05a3841f0461
Revises: ad45947d23d1
Create Date: 2018-12-26 15:45:30.051739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05a3841f0461'
down_revision = 'ad45947d23d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=128), nullable=False),
    sa.Column('alert_name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['alert_name'], ['alert.name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name', 'alert_name', name='_group_alert_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_alert')
    # ### end Alembic commands ###
