"""Add display name to tags

Revision ID: 13bff0d3319a
Revises: 442337e12ebe
Create Date: 2026-02-01 13:30:10.588022

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '13bff0d3319a'
down_revision = '442337e12ebe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()

    op.alter_column('alert', 'text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.add_column('tag', sa.Column('display_name', sa.Text(), server_default='TAG', nullable=False))

    conn.execute(sa.text("""
        UPDATE tag
        SET display_name = REPLACE(name, '_', ' ')
    """))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'display_name')
    op.alter_column('alert', 'text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###
