"""Using ids instead of index to keep track of lists

Revision ID: 230f40f0e35f
Revises: 6bf61c036e73
Create Date: 2025-10-27 11:14:43.640495

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '230f40f0e35f'
down_revision = '6bf61c036e73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('_lists_uc'), 'list_item', type_='unique')
    op.drop_column('list_item', 'index')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('list_item', sa.Column('index', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('_lists_uc'), 'list_item', ['list_name', 'index'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
