"""empty message

Revision ID: 2bc5a65f6bd6
Revises: 8d980410909e
Create Date: 2019-01-27 10:43:19.942967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bc5a65f6bd6'
down_revision = '8d980410909e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_alert', sa.Column('current_index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_alert', 'current_index')
    # ### end Alembic commands ###
