"""group_alerts

Revision ID: 3f4572aae7b3
Revises: ad45947d23d1
Create Date: 2019-01-26 19:38:17.192265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f4572aae7b3'
down_revision = 'ad45947d23d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_alert',
    sa.Column('group_name', sa.String(length=128), nullable=False),
    sa.Column('thumbnail', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('group_name', name=op.f('pk_group_alert'))
    )
    op.create_table('group_alert_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=128), nullable=False),
    sa.Column('alert_name', sa.String(length=128), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_name'], ['alert.name'], name=op.f('fk_group_alert_association_alert_name_alert')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group_alert_association')),
    sa.UniqueConstraint('group_name', 'alert_name', name='_group_alert_uc')
    )
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('alert', schema=None) as batch_op:
        batch_op.drop_column('thumbnail')

    op.drop_table('group_alert_association')
    op.drop_table('group_alert')
    # ### end Alembic commands ###
