"""group alerts

Revision ID: 8d980410909e
Revises: ad45947d23d1
Create Date: 2019-01-27 01:47:20.167797

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d980410909e'
down_revision = 'ad45947d23d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_alert',
    sa.Column('group_name', sa.String(length=128), nullable=False),
    sa.Column('thumbnail', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('group_name')
    )
    op.create_table('group_alert_association',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=128), nullable=False),
    sa.Column('alert_name', sa.String(length=128), nullable=False),
    sa.Column('index', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['alert_name'], ['alert.name'], ),
    sa.ForeignKeyConstraint(['group_name'], ['group_alert.group_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_name', 'alert_name', name='_group_alert_uc')
    )
    op.add_column('alert', sa.Column('thumbnail', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'thumbnail')
    op.drop_table('group_alert_association')
    op.drop_table('group_alert')
    # ### end Alembic commands ###
