"""adding chat message to group alerts

Revision ID: c22e186de4c0
Revises: c4157102f944
Create Date: 2019-04-16 23:25:07.289616

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22e186de4c0'
down_revision = 'c4157102f944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group_alert', sa.Column('chat_message', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('group_alert', 'chat_message')
    # ### end Alembic commands ###
