"""chatbot timers

Revision ID: c7acc817b580
Revises: 9291aaf2f1b0
Create Date: 2019-04-06 18:10:18.548574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7acc817b580'
down_revision = '9291aaf2f1b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timer',
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('interval', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('command')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timer')
    # ### end Alembic commands ###
