"""adding group alert chat fields

Revision ID: c82d9cb003c3
Revises: c4157102f944
Create Date: 2019-04-20 23:49:05.339848

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c82d9cb003c3'
down_revision = 'c4157102f944'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_alert") as batch_op:
        batch_op.add_column(sa.Column('always_chat', sa.Boolean(), server_default='f', nullable=True))
        batch_op.add_column(sa.Column('chat_message', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("group_alert") as batch_op:
        batch_op.drop_column('chat_message')
        batch_op.drop_column('always_chat')
    # ### end Alembic commands ###
