"""Reworking timers

Revision ID: de70b83f2201
Revises: 230f40f0e35f
Create Date: 2025-10-27 23:25:02.850558

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'de70b83f2201'
down_revision = '230f40f0e35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('bot_name', sa.Text(), nullable=False))
    op.add_column('timer', sa.Column('cron', sa.Text(), nullable=False))
    op.add_column('timer', sa.Column('next_time', sa.DateTime(timezone=True), nullable=False))
    op.drop_constraint('timer_command_key', 'timer', type_='unique')
    op.create_unique_constraint(None, 'timer', ['bot_name', 'command'])
    op.drop_column('timer', 'interval')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timer', sa.Column('interval', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'timer', type_='unique')
    op.create_unique_constraint(None, 'timer', ['command'])
    op.drop_column('timer', 'next_time')
    op.drop_column('timer', 'cron')
    op.drop_column('timer', 'bot_name')
    # ### end Alembic commands ###
