"""alias table

Revision ID: ea75d5756f19
Revises: 2bc5a65f6bd6
Create Date: 2019-03-03 15:54:02.117431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea75d5756f19'
down_revision = '2bc5a65f6bd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias',
    sa.Column('alias', sa.Text(), nullable=False),
    sa.Column('command', sa.Text(), nullable=False),
    sa.Column('badge', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('alias')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alias')
    # ### end Alembic commands ###
