""" Adding tag categories

Revision ID: fc872c81037a
Revises: ce9e3b3e702c
Create Date: 2025-08-10 00:27:58.187005

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'fc872c81037a'
down_revision = 'ce9e3b3e702c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('category', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tag', 'category')
    # ### end Alembic commands ###
